### ISSUE TITLE
*sometimes* can't see the server, can't join peer-hosted/people can't join me

### ISSUE THREAD

**Issue by Yeti995** [FishPhd/H2V-Online-Launcher#13]
the server is appearing somewhat randomly, and i cant join people and people cannot join me.
ports are forwarded, antivirus/firewall off, running .exes as admin, all files are in h2v directory, have deleted files and updated them back, etc
it worked perfectly fine on the first day (could see the server, could join others) but then not sure what happened afterwards.
a way i can make the server appear everytime is by changing the xlive config file (server = 1), but that still doesn't solve the peer-hosted problem.

**Comment by pnill** [comment]
Multiple issues you're reporting... 

So one by one,

1) Servers appearing and disappearing
This is a known issue and will be fixed in the next update.

2) Cannot join people or people cannot join you, it's uncommon for this to be both ways unless you're doing something like blocking the game with a firewall which you've mentioned you're not.

I would suggest making sure you have the most up to date DLL from here, and server = 0 is what you should be using not server = 1 as that will screw with your ports.

3) If you're attempting to run a dedicated server on the same system as your client, don't that will only cause you problems right now and could be part of the reason you're experiencing the issues that you are.

**Comment by Yeti995** [comment]
thanks, i'll keep the appearing and disappearing issue in mind.

yep im pretty sure i have the most up to date DLL. (according to the launcher it says i have updated to the newest version and can play), i've also tried downloading directly from this site. i'm not trying to run a dedicated server on any machine in my household.

**Comment by pnill** [comment]
Well, 
Other then that the only thing I can say is await the next update and see if it improves your issues if you still have them we'll work out additional debugging and try to pin point and fix the issue.
